### ISSUE TITLE
data.current(sid, "price")  shows nan

### ISSUE THREAD

**Issue by vbandaru** [alpacahq/pylivetrader#121]
Issue with getting current price on some symbols in pylivetrader. if i use rest api end point at the time of error thru postman, I get data back.

```
   ...: sid=symbol('WCG') 
   ...: sid 
   ...: current_price = data.current(sid, "price")  
   ...: current_price                                                                                                                                                                 
Out[2]: nan
```

**Comment by ttt733** [comment]
Hello @vbandaru, what API endpoint are you hitting to validate the data? Is it the Polygon API, or is it the Alpaca data API?

**Comment by shlomikushchi** [comment]
not all assets have price. WCG is an example to such asset.
this is basically not related to the repo (pylivetrader) because it's an api call.
you should check if there's available data for asset and act accordingly inside your code.

**Comment by vbandaru** [comment]
@ttt733 was using pylivetrader against paper a/c

**Comment by vbandaru** [comment]
> you should check if there's available data for asset and act accordingly inside your code.

can you show code snippet to check this?

**Comment by shlomikushchi** [comment]
@vbandaru if you want to check if a certain asset is a valid one you could use the pylivetrader shell.
you could run the shell like this:
`pylivetrader shell examples\MACD\macd_example.py --backend-config config.yaml`
*config.yaml should contain your API keys (check readme for more details)

now you could check if you can get data for a specific asset.
for eample:
data.history(symbol("AAPL"), "close", 10, "1d")
will yield:
![image](https://user-images.githubusercontent.com/7924802/79071327-ce5f6480-7ce3-11ea-85e3-197abfb09fc6.png)

and for WCG we will get an error because there is no available data.

**Comment by shlomikushchi** [comment]
I am closing this issue. if there is anything else, please let me know.
