### ISSUE TITLE
handle_data looping during the minute after close

### ISSUE THREAD

**Issue by teeling** [alpacahq/pylivetrader#128]
I have a problem where handle_data is running in a loop during the entire minute after the market close.
On line 110 in realtimeclock.py we have: 
`elif server_time == session_close:`
We don't test when self._last_emit was made, so we continuously loop for the entire minute.

Is this a bug, or am I misunderstanding something?
Also, shouldn't the last call to handle_data be at 15:59:00 for an exchange closing at 16:00:00?

**Comment by shlomikushchi** [comment]
you are correct. the fix should be a bit different than what you suggested.
Explanation:
so the realtimeclock is emitting signals and each one has a different meaning.
in this particular scenario 3 signals are emitted (yielded)
```
            elif server_time == session_close:
                self._last_emit = server_time
                if self.minute_emission:
                    yield server_time, MINUTE_END
                yield server_time, SESSION_END
```
BAR: a signal to call the users' code (handle_data)
MINUTE_END and SESSION_END: signals that are used for performance purposes. e.g: how did the algorithm performed against a benchmark. so they are not so relevant for this issue (but we will handle them separately.)

the solution for this issue is to not emit the BAR signal when the market is already closed (that only makes sense because market is closed).
that way handle_data is not called in a loop 

we may do a small refactoring for the performance signals as well, but this PR will give the users a quick fix for this issue.

**Comment by shlomikushchi** [comment]
the fix for this issue was meged to the master branch: https://github.com/alpacahq/pylivetrader/pull/134
closing the issue
