### ISSUE TITLE
Stop Order Rejected 

### ISSUE THREAD

**Issue by ikosenn** [alpacahq/pylivetrader#150]
Hi,
Last Friday I created an order using the `StopOrder` execution style. 

```python
from pylivetrader.finance.execution import StopOrder
from pylivetrader.api import order

order(‘AAPL’, 5, style=StopOrder(213.77)) 

```

`DEBUG: Alpaca: submitting stop order for AAPL - qty:7, side:buy, limit_price:None, stop_price:213.77`

The order went through but immediately got `REJECTED`. I saw this on the dashboard. Any ideas what could have gone wrong? My account had enough money for the buy

**Comment by shlomikushchi** [comment]
Hi, 
I'm not sure that I understand.
did you try to buy or to close shares using the StopOrder?

**Comment by ikosenn** [comment]
I did a buy. A `StopLimitOrder` works but on the paper account. When I do this on the live account the order goes through but is immediately rejected.
![Screenshot 2020-05-10 at 20 48 24](https://user-images.githubusercontent.com/5145715/81522532-bccba580-92ff-11ea-8cf7-08c734bd6814.png)

**Comment by shlomikushchi** [comment]
so this issue is not related to pylivetrader because the order is sent through the API.
you should open it here: https://github.com/alpacahq/alpaca-trade-api-python
just as a note, your stop limit range is very large (30$ apart). it is not a good practice to do that because it is basically a market order. 
it might be even related to that, but I don't know because there is no more info on the order.

**Comment by ikosenn** [comment]
I just tested this on the UI and the situation is the same. Something to do with having a stop loss because a limit order works. I'll close the issue and follow up with support. 
Thank you.

**Comment by ikosenn** [comment]
Correction. This was my fault I was using the stop limit order in an unexpected way.
