### ISSUE TITLE
Issue with pylivetrader for NAN values

### ISSUE THREAD

**Issue by abhikolekar** [alpacahq/pylivetrader#52]
My app is stuck in fetch with following warning. 
/app/.heroku/python/lib/python3.6/site-packages/zipline/pipeline/filters/filter.py:382: RuntimeWarning: invalid value encountered in less_equal
2018-11-16T19:42:48.281114+00:00 app[worker.1]: return (lower_bounds <= data) & (data <= upper_bounds)
2018-11-16T19:42:52.683746+00:00 app[worker.1]: 0

**Comment by umitanuki** [comment]
This warning should not be critical to stop your program but there should be something else. This error is issued since one of the pipeline code shifts numpy array by 1 with NaN padded, but it would not prevent any further operations.

Can you get more info about where your program is stuck? What data are you trying to fetch?

**Comment by ttt733** [comment]
Assuming this is fixed, closing.

**Comment by obvyah** [comment]
@abhikolekar hi, I've encountered the same issue,
could you tell me how to fix the issue as you mentioned?  thank you!

> My app is stuck in fetch with following warning.
> /app/.heroku/python/lib/python3.6/site-packages/zipline/pipeline/filters/filter.py:382: RuntimeWarning: invalid value encountered in less_equal
> 2018-11-16T19:42:48.281114+00:00 app[worker.1]: return (lower_bounds <= data) & (data <= upper_bounds)
> 2018-11-16T19:42:52.683746+00:00 app[worker.1]: 0
