### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by ckyleda** [alpacahq/pylivetrader#73]
When attempting to run the q01 example the following error occurs:

ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

Traceback (most recent call last):
  File "/home/[REMOVED]/.local/share/virtualenvs/q01-9tU7-qwB/bin/pylivetrader", line 7, in <module>
    from pylivetrader.__main__ import main
  File "/home/[REMOVED]/.local/share/virtualenvs/q01-9tU7-qwB/lib/python3.6/site-packages/pylivetrader/__init__.py", line 16, in <module>
    from pylivetrader import api # noqa
  File "/home/[REMOVED]/.local/share/virtualenvs/q01-9tU7-qwB/lib/python3.6/site-packages/pylivetrader/api.py", line 24, in <module>
    from pylivetrader.finance import execution, commission, slippage, cancel_policy
  File "/home/[REMOVED]/.local/share/virtualenvs/q01-9tU7-qwB/lib/python3.6/site-packages/pylivetrader/finance/execution.py", line 22, in <module>
    import pylivetrader.misc.math_utils as zp_math
  File "/home/[REMOVED]/.local/share/virtualenvs/q01-9tU7-qwB/lib/python3.6/site-packages/pylivetrader/misc/math_utils.py", line 53, in <module>
    nanmean = bn.nanmean
AttributeError: module 'bottleneck' has no attribute 'nanmean'

This is in a fresh pipenv after running pipenv install inside the example directory.

This could be due to the version of numpy (1.14.6) required not containing this module. However, official documentation on what _multiarray_umath actually is or when it was added is very sparse.

Testing numpy versions myself, I can import this module when using numpy 1.16.0rc2. Which dependency requires this version of numpy?

Has anyone run into this and resolved it?

**Comment by ckyleda** [comment]
This seems to be because bottleneck and bcolz aren't interacting correctly with the pipenv environment.

Installing them both manually via pip fixes this issue, but obviously you cannot do this on a heroku instance.

**Comment by umitanuki** [comment]
Recently someone else also reported numpy install issue in Heroku elsewhere. Something like https://github.com/heroku/heroku-buildpack-python/issues/704 is closest. There might be an issue in their CLI or something.

**Comment by ttt733** [comment]
https://github.com/quantopian/zipline/issues/997

It looks like this is a known issue that can be caused by several things. If a clean install isn't working for you, can you walk us through the installation path you're using? It could be a cached wheel like someone mentioned there, or it could somehow be switching numpy versions unexpectedly.

**Comment by ckyleda** [comment]
@ttt733

I'm simply running 'pipenv install' inside the q01 folder.

I did manage to resolve this by using pipenv to generate a requirements.txt and installing using pip, after which I was able to proceed.

**Comment by bibinmjose** [comment]
I have the same problem when I try to load a pickled file

```
     19 def load_pickle(path):
     20     with open(path, 'rb') as handle:
---> 21         return pickle.load(handle)
     22 
     23 

ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
```

**Comment by zchen0420** [comment]
> I have the same problem when I try to load a pickled file
> 
> ```
>      19 def load_pickle(path):
>      20     with open(path, 'rb') as handle:
> ---> 21         return pickle.load(handle)
>      22 
>      23 
> 
> ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
> ```

I have the same situation with numpy=1.16
I am safe with numpy=1.15

**Comment by batrlatom** [comment]
Had the same issue. Upgraded to numpy==1.16 and it works

**Comment by bibinmjose** [comment]
I have tried both and even checked out numpy's code. I can't find that module anywhere in numpy. Has anyone tried that?

**Comment by wingkitlee0** [comment]
>           I have tried both and even checked out numpy's code. I can't find that module ('numpy.core._multiarray_umath') anywhere in numpy. Has anyone tried that?

I found a few shared library files (*.so) in `numpy/core/` , such as `multiarray.cpython-36m-x86_64-linux-gnu.so` .

**Comment by bibinmjose** [comment]
@saforem2 Me too noticed the problem when i try to unpickle a pickled array from another computer. I got around it by not using python's statistics functions instead of numpy's. I tried to install numpy==16 but the story is the same . I was **not** able to upgrade numpy-base to 1.14 since it uninstalls a lot of dependencies. Well, solution ended up not using numpy functions.

**Comment by bibinmjose** [comment]
@saforem2 are you picking any nupy objects ? Try using another library

**Comment by saforem2** [comment]
@bibinmjose I believe the error occurred when trying to load a normal dictionary (containing some numpy arrays as values). I switched to a different conda environment with `numpy.__version__=1.16.0` and `pickle.format_version=4.0` and it seems to work fine so I was able to get around the issue.

**Comment by jainraje** [comment]
I have this error recently since a few changes on my MAC. I followed all the best practices and can't seem to resolve this error.

1) Upgraded to MAC High Sierra (10.13.6)

2) installed both python 3.6 and python 3.7 to run side by side using home-brew and followed the guidelines presented here:
https://stackoverflow.com/questions/51726203/installing-python3-6-alongside-python3-7-on-mac

3) setup new virtual env to use python 3.6 and a bunch of other modules.

This error occurs in the virtual environment. Both notebooks and command line python code generate the error. The python code runs 100% correctly with no other errors than this message.

python my_py_file.py 
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

I deleted and recreated the venv but the error persists. Likely all the code continues to run without any other errors.

I'm not sure what to do next. I do not like this error message. Any suggestions will be welcome.

**Comment by jainraje** [comment]
FYI, I just resolved this issue by forcing a reinstall of numpy and pandas as follows:

pip install --upgrade --force-reinstall numpy==1.14.5
pip install --upgrade --force-reinstall pandas==0.22.0

No more error message.

**Comment by wishvivek** [comment]
1. Solved it by using 'pip install numpy==1.16'
2. Was using conda install numpy before that. The conda install option was throwing the same issue.

**Comment by TshepoMK** [comment]
> Inside a new conda virtual environment,
> 
> 1. Solved it by using pip install numpy==1.16
> 2. Was using conda install numpy before that. The conda install option was throwing the same issue.

Thanks man, I installed numpy 1.16 and it fixed the issue.

**Comment by Memento1990** [comment]
> Inside a new conda virtual environment,
> 
> 1. Solved it by using pip install numpy==1.16
> 2. Was using conda install numpy before that. The conda install option was throwing the same issue.

Thanks man, it solves the problem.

**Comment by ttt733** [comment]
I've updated the numpy requirement to 1.16 across our various pylivetrader releases, and we'll try to keep the required numpy version as updated as possible, so this issue should not crop up anymore.

**Comment by Adarshsng** [comment]
updrage numpy to latest version it solves the problem ^.^

**Comment by live-wire** [comment]
`pip install --upgrade numpy`

**Comment by bibinmjose** [comment]
@live-wire Problem is most often upgrading numpy will cause broken dependencies in other packages

https://github.com/alpacahq/pylivetrader/issues/73#issuecomment-470851827

**Comment by ninofiliu** [comment]
@bibinmjose How come? I though that `1.15 -> 1.16` = minor update = no breaking changes

**Comment by bibinmjose** [comment]
@ninofiliu There was some compatibility issue with my tensorflow version and it was not upgrading numpy citing conflicts. Anyways, I have moved on and it's no longer an issue for me. 

https://github.com/alpacahq/pylivetrader/issues/73#issuecomment-481001280

**Comment by VineetJain22** [comment]
I am facing a similar issue when trying to load a pickled file. Code, error & versions below.
Code:
infile = open('_test_suite.pkl','rb')
new_dict = pickle.load(infile)
infile.close()
Error:
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-16-c661657313e7> in <module>()
      1 infile = open('_test_suite.pkl','rb')
----> 2 new_dict = pickle.load(infile)
      3 infile.close()

ModuleNotFoundError: No module named 'core'
Version:
Numpy 1.16.2
Pandas 0.24.2
Pickle 4.0

Tried pandas.read_pickle() too. It gives a similar No module named 'core' error.

Any suggestion will be helpful.

**Comment by AmanOswal** [comment]
Had the same issue. Reinstalling numpy fixed it

**Comment by 13540148299** [comment]
Same issue. Upgrading numpy to 1.16  fixed it,thanks

**Comment by Hedibouchelliga** [comment]
for future readors , this how i fixed it :
pip uninstall numpy
then delete the folder with the name numpy
conda -c install numpy 
and that's how it works

**Comment by zhangleibo** [comment]
--- import sys ---
Traceback (most recent call last):
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\core\__init__.py", line 22, in <module>
    from . import multiarray
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./Python\func.py", line 5, in <module>
    from modSymmetryLanding import modSymmetryLanding
  File "./Python\modSymmetryLanding.py", line 6, in <module>
    import numpy as np
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import core
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\core\__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.6 from "D:\worker\LGAS\LandingGearsAnalysisSystem\..\bin\Debug\LGAnalysisSystem.exe"
  * The NumPy version is: "1.19.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'

2020-09-24 16:07:54:027 [Inf]CInterface::CallPython,Line=166 ******************** Python end ****
